version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.dockerfile
      context: .
    image: samplant10/unidocker:php
    restart: always
    volumes:
      - "./UniVulnerableWebsite/:/var/www/html/"
    ports:
      - 8080:80
    links:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tiaspbiqe2r
      MYSQL_DATABASE: university
    volumes:
    - mysql-data:/var/lib/mysql
    - "./uni.sql:/tmp/uni.sql"

  vulndocker:
    build:
      dockerfile: vulnerableCont.dockerfile
      context: .
    image: samplant10/unidocker:vulncont
    restart: on-failure
    ports:
      - 21
      - 2222

    volumes:
      - user-data-ftp:/home/

volumes:
  mysql-data:
  user-data-ftp: